---
- name: create group sysadmin
  group:
    name: sysadmin
    state: present
    gid: 1750

- name: Create sysadmin user
  user:
    name: sysadmin
    uid: 1040
    create_home: true
    group: sysadmin
