---
- name: Provision VM
  hosts: all
  become: yes
  become_method: sudo
  remote_user: debian
  tasks:
    - import_tasks: "roles/general/users_groups.yml"
    - import_tasks: "roles/angular/tasks/nodejs.yml"
    - import_tasks: "roles/angular/tasks/fronted.yml"
